import "./globals.css";
import NavBar from "@/Componanats/NavBar/NavBar"

export const metadata = {
  title: "Kick Off",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <main className="main">{children}</main>
      </body>
    </html>
  );
}
